# This file provides instructions for packaging.

`Types-XSD`
	perl_version_from m`Types::XSD`;
	version_from      m`Types::XSD`;
	readme_from       m`Types::XSD`;
	requires          p`DateTime::Incomplete 0`;
	requires          p`DateTimeX::Auto 0`;
	requires          p`Type::Library 0.004`;
	requires          p`XML::RegExp 0`;
	test_requires     p`Test::More 0.88`;
	test_requires     p`Test::TypeTiny 0.004`;
.

